### ISSUE TITLE
Can't figure out why slackOOO isn't working

### ISSUE THREAD

**Issue by diegodossantos** [shaunburdick/slack-ooo-personal#18]
Start by saying I'm not a developer. I installed slackooo using npm, got my slack token. I've been running `npm test`, but am having trouble figuring out what's not working. Do you have a code snippet of a working version of config.js or of what the npm test results should look like? Thank you!

**Comment by shaunburdick** [comment]
do you have an example of the errors you are getting?

**Comment by diegodossantos** [comment]
Thanks for the reply, @shaunburdick.  There are no errors; there were a few, but I fixed them. Below the last table, I see:
`total:     23
  passing:   23
  duration:  2.3s`

Which I interpret as nothing wrong, but after I add the date, and save it, nothing happens when someone @mentions or DMs me.

**Comment by shaunburdick** [comment]
The tests I wrote only check to make sure the code written does what it should. It won't test you installation.
Things to check:
- if you want the bot to respond to direct messages, make sure `app.respond.dm` is `true`
- same goes for mentions in channels, make sure `app.respond.channel` is `true`
- Check the output of the app when it starts
  - You should see something like: `Welcome to Slack. You are @<your username> of <Your Slack Name>` *Make sure those are correct*
  - Make sure your start date is correct. If it's in the future, the bot will not respond until then and you will see a message like: `Waiting until Wed Jul 19 2017 08:00:00 GMT-0400 (EDT) to start bot...`
- You should also see a message in your personal dm channel (under direct messages that has your name and (you) next to it):
![image](https://user-images.githubusercontent.com/5100175/28320545-dc9641a8-6b9e-11e7-9db7-81fedcd3de1b.png)

If you'd like, post the output of the app when you start it (`npm start`) or direct message it to me.

**Comment by diegodossantos** [comment]
Thank you, @shaunburdick. Here's what I'm getting. I appreciate your help. Let me know what I should do from here.

<img width="761" alt="screen shot 2017-07-21 at 2 21 54 pm" src="https://user-images.githubusercontent.com/1638600/28476986-17bfdbe4-6e20-11e7-9b9f-9aea8074d76e.png">

**Comment by shaunburdick** [comment]
So the error you are getting is saying it could not parse your endtime. it needs to be in a parsable format: http://dygraphs.com/date-formats.html
What is the value you put?

**Comment by diegodossantos** [comment]
Found a trailing `a` on my end time 😩. Can't believe I couldn't read that error, though. 

I think I'm almost there now. The error now is: `error: uncaughtException: this.config.app.respond.keywords.join is not a function `

Thank you so much, again.

**Comment by shaunburdick** [comment]
keywords needs to be an array, even if it's empty

**Comment by diegodossantos** [comment]
🙌
