### ISSUE TITLE
Start time not working properly

### ISSUE THREAD

**Issue by jandreaucodes** [shaunburdick/slack-ooo-personal#21]
![99rgp](https://user-images.githubusercontent.com/12860371/28675569-473b6d9e-72b6-11e7-9bd1-201d9ba66b91.png)

You can see here I've set my start time to 2017/09/17 00:00:00, but the bot thinks I've set it to September 16th at 8pm.

I also tried using milliseconds (1505102400000) and that made the bot crash on Heroku because it couldn't decipher the time in milliseconds.

**Comment by shaunburdick** [comment]
You need to specify a timezone otherwise it will use the TZ of the server it's running on. I would recommend the [ISO-8601 format](https://www.iso.org/iso-8601-date-and-time-format.html): `2017-09-17T00:00:00-0400`

**Comment by jandreaucodes** [comment]
Perfect. That did the trick.

Thanks for _all_ your help!

**Comment by shaunburdick** [comment]
No problem. I will update the README to use ISO-8601 format. The other formats are hit or miss sometimes.

**Comment by jandreaucodes** [comment]
Quick question: Shouldn't APP_TIMEBOX_START prevent the bot from responding _before_ that time?

I just tested on production with APP_TIMEBOX_START set to September 10 and the bot still responded.

**Comment by shaunburdick** [comment]
Your start date is too far into the future, it's probably overload the INT32 and just starting. It's in the same box as END. It's a language restriction :-/

**Comment by jandreaucodes** [comment]
No worries. I just turned off the dyno in Heroku and will toggle it back on the Friday before I go on leave. 😄

**Comment by shaunburdick** [comment]
Yeah, it never really occurred to me that someone would want to start the bot and let it sit there for 2 months before it did anything ;-)
