### ISSUE TITLE
Response in public channel is not working

### ISSUE THREAD

**Issue by jandreaucodes** [shaunburdick/slack-ooo-personal#22]
I've turned APP_RESPOND_CHANNEL to true, but the bot is still not responding in a public channel.

I'm in that channel, so the bot should be able to respond, but it's not responding at all.

Is there something else I'm missing?

**Comment by shaunburdick** [comment]
Nope, that should do it. The bot should respond once your are specifically mentioned (ie: `@mikeatdesk are you there?`) Keep in mind that once it responds in the channel, it won't respond again for another 5 minutes.

**Comment by jandreaucodes** [comment]
Gotcha, it's looking for @user ANYThing. Just @user doesn't trigger it.

The channel response seems to be affected by #23 as well, FYI.
