### ISSUE TITLE
APP_RESPOND_DMPREFIX not honored

### ISSUE THREAD

**Issue by jandreaucodes** [shaunburdick/slack-ooo-personal#23]
I have APP_RESPOND_DMPREFIX set to _just_ "Hello ${user}. I'm currently out of the office.", but the bot's responding with "Hello ${user}. I'm currently out of the office with message:"

It seems to be ignoring the custom APP_RESPOND_DMPREFIX (or I have something setup wrong).

**Comment by shaunburdick** [comment]
`APP_RESPONSE_DMPREFIX`

**Comment by jandreaucodes** [comment]
Interesting. When it cloned to Heroku, it came through as APP_RESPOND for both DM and CHANNEL prefix.

I just changed them and it's working now.  You should check out why it imported them incorrectly in the first place. :-)
