### ISSUE TITLE
End Date greater than 24 days

### ISSUE THREAD

**Issue by jandreaucodes** [shaunburdick/slack-ooo-personal#24]
Tried to set my end date 6 months in the future (for patenity leave):

`32 Int overflow error!
Wed Mar 14 2018 10:30:00 GMT+0000 (UTC) is too far into the future.
Set this to something less than 24 days or 0`

I set it back to 0, but it'd be nice to be able to set extended periods of time.

**Comment by shaunburdick** [comment]
Right, Node doesn't support timeouts larger than the max 32bit integer. It can't go further than this.
