### ISSUE TITLE
Doesn't seem to receive messages?

### ISSUE THREAD

**Issue by ChuckJonas** [shaunburdick/slack-ooo-personal#5]
I've hooked it up (using a [Slack Test Token](https://api.slack.com/docs/oauth-test-tokens)), but it doesn't seem to ever receive messages.

I've added debugging statements in the entry to the Bot.handleMessage() function, but they never run no matter how messages are sent (DM, channel, mention, ETC).  

RTM seems to connect fine, but `this.controller.on('direct_message,direct_mention,mention', (bot, message) => {` never fires for events.

**Comment by shaunburdick** [comment]
Does the output say what channels you are a member of?
That trigger only happens when that account is mentioned or direct messages, IE
`@account Are you there?`
`Anyone seen @account?`

**Comment by shaunburdick** [comment]
was that it?
